version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U devuser']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
